// Copyright 2012, Bryan Matsuo. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

/*  Filename:    doc.go
 *  Author:      Bryan Matsuo <bryan.matsuo [at] gmail.com>
 *  Created:     2012-08-12 17:11:47.70504 -0700 PDT
 *  Description: documentation file
 */

/*
Package webapi is a toolkit for building web server APIs. It provides an
interface for different types of APIs. For an example API implementation see
github.com/bmatsuo/webapi/jsonapi.

Params

API parameters are a set of arbitrary values indexed by strings. Parameters are
retreived for an request r with

	params := webapi.Params(r)

Params are generated by the Params method of type implementing Interface.

Errors

Fatal errors encountered during WebAPI.Params parsing should be returned as an
Error. Errors are used to create an *http.Response instead of calling
Interface.ServeHTTP.

Errors are implemented as an interface. This allows errors to marshal response
data in a convenient way.
*/
package webapi
